name: wings
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  flutter_riverpod: ^1.0.4
  # auto_route: ^4.0.1
  auto_route: ^4.2.1
  logger: ^1.1.0
  cloud_firestore: ^3.1.15
  
  cloud_firestore_odm: ^1.0.0-dev.20
  # fluttertoast: ^8.0.9
  
  shared_preferences: ^2.0.15
  json_annotation:
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  file_selector: ^0.8.4+3
  uuid: ^3.0.6
  auto_size_text: ^3.0.0
  
  share_plus: ^4.0.10
  # get: ^4.6.5
  hashtagable: ^2.1.0
  riverpod: ^1.0.3
  auth_buttons: ^3.0.0
  google_sign_in: ^5.4.0
  velocity_x: ^3.5.1
  firebase_storage: ^10.3.2
  chat_bubbles: ^1.3.0
  timeago: ^3.2.2
  # firebase_messaging: ^12.0.0
  # flutter_local_notifications: ^9.7.0
  http: ^0.13.4
  onesignal_flutter: ^3.3.2
  fluttertoast: ^8.0.9
  # image_picker_for_web: ^2.1.8
  # story_creator: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  auto_route_generator: 
  cloud_firestore_odm_generator: ^1.0.0-dev.20
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  