// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVLalOkCi-Zs0CRzo5pH8J06z6X7V2hAI',
    appId: '1:727523993205:web:5b8c2fccf2f4f6091eba3c',
    messagingSenderId: '727523993205',
    projectId: 'wings-18365',
    authDomain: 'wings-18365.firebaseapp.com',
    storageBucket: 'wings-18365.appspot.com',
    measurementId: 'G-BRZ8FXZZ5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEf1AsNAijFXEn8ttxlzdjg7PdFQEPcRQ',
    appId: '1:727523993205:android:855c704ff0b192c71eba3c',
    messagingSenderId: '727523993205',
    projectId: 'wings-18365',
    storageBucket: 'wings-18365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKQ8ZM_LEsy3RhzCcEF3sWNpoNvwrgaFw',
    appId: '1:727523993205:ios:dbf27cea1f29ca6c1eba3c',
    messagingSenderId: '727523993205',
    projectId: 'wings-18365',
    storageBucket: 'wings-18365.appspot.com',
    iosClientId: '727523993205-8k02l5fn502sfpfevjkn6vvc11b5qatn.apps.googleusercontent.com',
    iosBundleId: 'com.wings.wings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKQ8ZM_LEsy3RhzCcEF3sWNpoNvwrgaFw',
    appId: '1:727523993205:ios:dbf27cea1f29ca6c1eba3c',
    messagingSenderId: '727523993205',
    projectId: 'wings-18365',
    storageBucket: 'wings-18365.appspot.com',
    iosClientId: '727523993205-8k02l5fn502sfpfevjkn6vvc11b5qatn.apps.googleusercontent.com',
    iosBundleId: 'com.wings.wings',
  );
}
